"""Outbound notification service for TrustSphere."""

from __future__ import annotations

from datetime import datetime, timedelta
import html
import re
import sys

from flask import current_app, url_for


class NotificationService:
    """Send email and demo notification messages."""

    @classmethod
    def send_email(cls, to_email, subject, body_html, body_text=None):
        """Send an HTML email through Flask Mail."""
        try:
            from flask_mail import Message

            from app.extensions import mail

            msg = Message(
                subject=subject,
                recipients=[to_email],
                html=body_html,
                body=body_text or cls.strip_html(body_html),
            )
            mail.send(msg)
            return True, "Email sent"
        except Exception as exc:
            print(f"[NotificationService] Email send failed: {exc}", file=sys.stderr)
            return False, str(exc)

    @staticmethod
    def strip_html(html_string):
        """Convert simple HTML to plain text."""
        try:
            import bleach

            return bleach.clean(html_string or "", tags=[], strip=True)
        except Exception:
            return re.sub(r"<[^>]+>", "", html_string or "")

    @classmethod
    def send_alert_notification_email(cls, alert_id):
        """Notify an assigned analyst about an alert."""
        try:
            from app.models import AdminUser, Alert

            alert = Alert.query.get(alert_id)
            if not alert:
                return False, "Alert not found"
            analyst = alert.assigned_analyst
            if not analyst:
                analyst = AdminUser.query.filter(
                    AdminUser.institution_id == alert.institution_id,
                    AdminUser.role.in_(["security_analyst", "compliance_officer", "super_admin"]),
                    AdminUser._is_active.is_(True),
                ).first()
            if not analyst:
                return False, "No analyst email available"

            detail_url = url_for("admin.alert_detail", alert_id=alert.id, _external=True)
            body = cls.build_email_html(
                title=alert.title,
                body_paragraphs=[
                    f"Severity: {alert.severity.upper()}",
                    alert.description or "A TrustSphere alert requires analyst review.",
                ],
                cta_text="Open Alert",
                cta_url=detail_url,
                footer_note="This message was generated by TrustSphere alert monitoring.",
            )
            subject = f"[{alert.severity.upper()}] TrustSphere Alert: {alert.title}"
            return cls.send_email(analyst.email, subject, body)
        except Exception as exc:
            print(f"[NotificationService] Alert notification failed: {exc}", file=sys.stderr)
            return False, str(exc)

    @classmethod
    def send_password_reset_email(cls, user_type, user_id, reset_token):
        """Send a password reset email for admin or portal users.

        user_type: "admin" or "user"
        user_id: the primary key of the user record
        """
        try:
            if user_type == "admin":
                from app.models import AdminUser as _AdminUser

                user = _AdminUser.query.get(user_id)
            else:
                from app.models import User as _User

                user = _User.query.get(user_id)

            if not user or not getattr(user, "email", None):
                return False, "User not found or no email available"

            reset_url = url_for("auth.reset_password", token=reset_token, _external=True)
            # Use a generic, user-facing message for portal users and a slightly different
            # message for administrators to reflect their elevated access.
            if user_type == "admin":
                paragraphs = [
                    "We received a request to reset your TrustSphere administrator password.",
                    "This link expires in 1 hour. If you did not request this, ignore this email and review your account activity.",
                ]
            else:
                paragraphs = [
                    "We received a request to reset your TrustSphere account password.",
                    "This link expires in 1 hour. If you did not request this, you can ignore this email.",
                ]

            body = cls.build_email_html(
                title="Password Reset Request",
                body_paragraphs=paragraphs,
                cta_text="Reset Password",
                cta_url=reset_url,
                footer_note="Never share this link with anyone.",
            )
            return cls.send_email(
                user.email,
                "TrustSphere Password Reset Request",
                body,
            )
        except Exception as exc:
            print(f"[NotificationService] Password reset email failed: {exc}", file=sys.stderr)
            return False, str(exc)

    @classmethod
    def send_email_verification(cls, admin_user_id, verify_token):
        """Send an admin email verification message."""
        try:
            from app.models import AdminUser

            admin_user = AdminUser.query.get(admin_user_id)
            if not admin_user:
                return False, "Admin user not found"
            verify_url = url_for("auth.verify_email", token=verify_token, _external=True)
            body = cls.build_email_html(
                title="Verify Your Email Address",
                body_paragraphs=[
                    "Please verify this email address to activate your TrustSphere administrator account.",
                    "The verification link helps protect your institution access.",
                ],
                cta_text="Verify Email",
                cta_url=verify_url,
                footer_note="You can ignore this email if you did not create this account.",
            )
            return cls.send_email(
                admin_user.email,
                "TrustSphere Verify Your Email Address",
                body,
            )
        except Exception as exc:
            print(f"[NotificationService] Verification email failed: {exc}", file=sys.stderr)
            return False, str(exc)

    @classmethod
    def send_stepup_notification(cls, user_id, method, challenge_data):
        """Simulate step up notification delivery."""
        try:
            if method == "otp":
                # Send the OTP to the user's registered email address in real deployments.
                try:
                    from app.models import User

                    user = User.query.get(user_id)
                    otp_code = (challenge_data or {}).get("otp_code")
                    # Console demo output for local debugging
                    print(
                        f"[DEMO OTP] User {user_id}: Your TrustSphere security code is {otp_code}. Valid for 2 minutes."
                    )
                    if user and getattr(user, "email", None) and otp_code:
                        subject = "TrustSphere verification code"
                        body = cls.build_email_html(
                            title="Your verification code",
                            body_paragraphs=[
                                f"Your verification code is {otp_code}.",
                                "This code is valid for 2 minutes.",
                            ],
                            footer_note="If you did not request this code, please ignore this message.",
                        )
                        ok, message = cls.send_email(user.email, subject, body)
                        if not ok:
                            print(f"[NotificationService] Failed to send OTP email: {message}", file=sys.stderr)
                        return ok, message
                except Exception as exc:
                    print(f"[NotificationService] Step up email failed: {exc}", file=sys.stderr)
                    # Fall through to demo behaviour if email sending fails
            elif method == "push_notification":
                print(f"[DEMO PUSH] Sending push notification to user {user_id}'s registered device.")
            elif method == "video_kyc":
                print(f"[DEMO VIDEO KYC] Video KYC session initiated for user {user_id}.")
            elif method == "agent_call":
                print(f"[DEMO AGENT CALL] Agent call queued for user {user_id}.")
            else:
                print(f"[DEMO STEPUP] Method {method} initiated for user {user_id}.")
            return True, method
        except Exception as exc:
            print(f"[NotificationService] Step up notification failed: {exc}", file=sys.stderr)
            return False, str(exc)

    @classmethod
    def send_account_recovery_status_email(cls, user_id, status, institution_id):
        """Notify a customer about account recovery status in demo mode."""
        try:
            from app.models import Institution, User

            user = User.query.get(user_id)
            institution = Institution.query.get(institution_id)
            status_labels = {
                "initiated": "Recovery request initiated",
                "verified": "Recovery request verified",
                "denied": "Recovery request denied",
                "manual_review": "Recovery request sent for manual review",
            }
            masked_user = user.get_masked_id() if user else "***"
            institution_name = institution.name if institution else "TrustSphere"
            print(
                f"[DEMO ACCOUNT RECOVERY] {institution_name} user {masked_user}: "
                f"{status_labels.get(status, status)}"
            )
            return True, status
        except Exception as exc:
            print(f"[NotificationService] Account recovery notification failed: {exc}", file=sys.stderr)
            return False, str(exc)

    @classmethod
    def send_weekly_security_digest(cls, institution_id):
        """Send weekly alert digest to compliance and super admin users."""
        try:
            from app.models import AdminUser
            from app.services.report_generator import ComplianceReportGenerator

            date_to = datetime.utcnow()
            date_from = date_to - timedelta(days=7)
            report = ComplianceReportGenerator.generate_alert_summary_report(
                institution_id,
                date_from,
                date_to,
            )
            recipients = AdminUser.query.filter(
                AdminUser.institution_id == institution_id,
                AdminUser.role.in_(["compliance_officer", "super_admin"]),
                AdminUser._is_active.is_(True),
            ).all()
            body = cls.build_email_html(
                title="Weekly Security Digest",
                body_paragraphs=[
                    f"Total alerts: {sum(report.get('severity_counts', {}).values())}",
                    f"Open alerts: {report.get('resolution_stats', {}).get('open', 0)}",
                    f"Average resolution hours: {report.get('average_resolution_hours', 0.0)}",
                ],
                footer_note="Generated by TrustSphere compliance reporting.",
            )
            sent = 0
            for admin_user in recipients:
                ok, _message = cls.send_email(
                    admin_user.email,
                    "TrustSphere Weekly Security Digest",
                    body,
                )
                if ok:
                    sent += 1
            return sent
        except Exception as exc:
            print(f"[NotificationService] Weekly digest failed: {exc}", file=sys.stderr)
            return 0

    @classmethod
    def send_demo_request_notification(cls, contact_data_dict):
        """Send an internal email for a new demo request."""
        try:
            to_email = current_app.config.get("DEFAULT_ADMIN_EMAIL", "admin@trustsphere.com")
            rows = []
            for key, value in (contact_data_dict or {}).items():
                label = str(key).replace("_", " ").title()
                rows.append(f"{label}: {value}")
            body = cls.build_email_html(
                title="New Demo Request",
                body_paragraphs=rows or ["A new demo request was received."],
                footer_note="Generated by the public TrustSphere website.",
            )
            return cls.send_email(
                to_email,
                "TrustSphere New Demo Request",
                body,
            )
        except Exception as exc:
            print(f"[NotificationService] Demo request notification failed: {exc}", file=sys.stderr)
            return False, str(exc)

    @classmethod
    def build_email_html(cls, title, body_paragraphs, cta_text=None, cta_url=None, footer_note=None):
        """Build a compact inline styled email template."""
        try:
            safe_title = html.escape(title or "TrustSphere")
            paragraphs = "".join(
                f'<p style="margin:0 0 14px;color:#1f2937;line-height:1.55;">{html.escape(str(paragraph))}</p>'
                for paragraph in (body_paragraphs or [])
            )
            cta = ""
            if cta_text and cta_url:
                cta = (
                    '<table role="presentation" cellspacing="0" cellpadding="0" style="margin:24px 0;">'
                    "<tr><td>"
                    f'<a href="{html.escape(cta_url)}" '
                    'style="background:#d4a72c;color:#111827;text-decoration:none;'
                    'padding:12px 18px;border-radius:4px;font-weight:700;display:inline-block;">'
                    f"{html.escape(cta_text)}</a>"
                    "</td></tr></table>"
                )
            footer = html.escape(footer_note or "TrustSphere security notification")
            year = datetime.utcnow().year
            return (
                '<div style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,Helvetica,sans-serif;">'
                '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f4f6;">'
                '<tr><td align="center" style="padding:24px;">'
                '<table role="presentation" width="640" cellspacing="0" cellpadding="0" '
                'style="width:100%;max-width:640px;background:#ffffff;border:1px solid #e5e7eb;">'
                '<tr><td style="background:#0f2742;color:#ffffff;padding:20px 24px;font-size:20px;font-weight:700;">'
                "TrustSphere"
                "</td></tr>"
                f'<tr><td style="padding:28px 24px;"><h2 style="margin:0 0 16px;color:#111827;font-size:22px;">{safe_title}</h2>'
                f"{paragraphs}{cta}</td></tr>"
                f'<tr><td style="padding:18px 24px;background:#f9fafb;color:#6b7280;font-size:12px;">{footer}<br>'
                f"&copy; {year} TrustSphere</td></tr>"
                "</table></td></tr></table></div>"
            )
        except Exception as exc:
            print(f"[NotificationService] Email template build failed: {exc}", file=sys.stderr)
            return "<p>TrustSphere notification</p>"
