"""Security alert model."""

from datetime import datetime
import uuid

from app.extensions import db


class Alert(db.Model):
    """Security alert generated by TrustSphere."""

    __tablename__ = "alerts"

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    institution_id = db.Column(
        db.String(36),
        db.ForeignKey("institutions.id"),
        nullable=False,
        index=True,
    )
    session_id = db.Column(db.String(36), db.ForeignKey("session_records.id"), nullable=True)
    user_id = db.Column(db.String(36), db.ForeignKey("users.id"), nullable=True, index=True)
    alert_type = db.Column(db.String(50), nullable=False, index=True)
    severity = db.Column(db.String(20), nullable=False, index=True)
    ml_priority_score = db.Column(db.Float, default=0.5, index=True)
    status = db.Column(db.String(20), nullable=False, default="open", index=True)
    assigned_to = db.Column(db.String(36), db.ForeignKey("admin_users.id"), nullable=True)
    auto_action_taken = db.Column(db.String(50), default="none")
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=True)
    analyst_notes = db.Column(db.Text, nullable=True)
    resolved_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False, index=True)

    institution = db.relationship("Institution", back_populates="alerts")
    user = db.relationship("User", back_populates="alerts")
    session = db.relationship("SessionRecord", back_populates="alerts")
    assigned_analyst = db.relationship(
        "AdminUser",
        foreign_keys=[assigned_to],
        back_populates="assigned_alerts",
    )

    def get_severity_color(self):
        """Return Bootstrap color class for severity."""
        return {
            "low": "success",
            "medium": "warning",
            "high": "danger",
            "critical": "danger",
        }.get(self.severity, "secondary")

    def get_severity_badge_color(self):
        """Return Bootstrap color class for severity badges."""
        return self.get_severity_color()

    def get_severity_icon(self):
        """Return Bootstrap Icons class for severity."""
        return {
            "low": "bi-info-circle",
            "medium": "bi-exclamation-triangle",
            "high": "bi-exclamation-octagon",
            "critical": "bi-x-octagon-fill",
        }.get(self.severity, "bi-info-circle")

    def get_status_badge_color(self):
        """Return Bootstrap color class for status."""
        return {
            "open": "secondary",
            "investigating": "primary",
            "resolved": "success",
            "dismissed": "dark",
            "false_positive": "info",
        }.get(self.status, "secondary")

    def get_alert_type_display(self):
        """Return human readable alert type."""
        labels = {
            "ato_attempt": "Account Takeover Attempt",
            "insider_anomaly": "Insider Anomaly",
            "kyc_fraud": "KYC Fraud",
            "new_device": "New Device",
            "impossible_travel": "Impossible Travel",
            "bulk_export": "Bulk Export",
            "suspicious_behaviour": "Suspicious Behaviour",
            "account_recovery_abuse": "Account Recovery Abuse",
            "credential_stuffing": "Credential Stuffing",
            "session_hijacking": "Session Hijacking",
        }
        return labels.get(self.alert_type, (self.alert_type or "").replace("_", " ").title())

    def to_dict(self):
        """Return all alert fields."""
        return {
            "id": self.id,
            "institution_id": self.institution_id,
            "session_id": self.session_id,
            "user_id": self.user_id,
            "alert_type": self.alert_type,
            "alert_type_display": self.get_alert_type_display(),
            "severity": self.severity,
            "ml_priority_score": self.ml_priority_score,
            "status": self.status,
            "assigned_to": self.assigned_to,
            "auto_action_taken": self.auto_action_taken,
            "title": self.title,
            "description": self.description,
            "analyst_notes": self.analyst_notes,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

    def __repr__(self):
        return f"<Alert {self.alert_type} severity={self.severity} status={self.status}>"
